### ISSUE TITLE
DontDestroyOnLoad

### ISSUE THREAD

**Issue by rocky1138** [thestonefox/SteamVR_Unity_Toolkit#273]
Attaching a DontDestroyOnLoad script to your SteamVR Camera Rig object then using Bezier pointers will cause a null exception on their first use after a level change. I am not entirely sure how to solve this. Any hints/docs/tutorials you might be able to point me toward?

Should I be dynamically adding the Bezier script to my controllers at run time?

**Comment by thestonefox** [comment]
I'll take a look at this on the live stream in a couple of hours. Hopefully I can figure out where the issue is.

**Comment by rocky1138** [comment]
That would be amazing. Thank you.

**Comment by thestonefox** [comment]
Hey,

I looked into this, whilst it's easy to fix the issue with VRTK, it seems SteamVR still crashes when you try and persist the CameraRig across scene loads. So even with VRTK fixed you're still going to have errors because of the core SteamVR plugin :(

**Comment by thestonefox** [comment]
Actually, Looking at this forum, looks as if you can hack the SteamVR_Render code so it does survive a scene load:

http://forum-old.unity3d.com/threads/moving-camerarig-between-scenes-without-destroying-steamvr.407169/

So I'll apply the fix to VRTK, but you'll have to modify your local version of SteamVR for it to work.

**Comment by thestonefox** [comment]
Fixed in commit: https://github.com/thestonefox/SteamVR_Unity_Toolkit/commit/74f8a09c78330a0ed365f1b5ed12f3c7166c9b9e

**Comment by rocky1138** [comment]
Wow! Thank you so much. Is there anywhere that the stream was recorded? I couldn't find a link anywhere to your stuff.

**Comment by thestonefox** [comment]
I'm streaming it right now :) https://www.twitch.tv/thestonefox

**Comment by rocky1138** [comment]
I am still receiving errors after pulling the latest revision, unfortunately. Pasted this into your Twitch as well.

MissingReferenceException: The object of type 'GameObject' has been destroyed but you are still trying to access it.
Your script should either check if it is null or you should not destroy the object.
VRTK.VRTK_BezierPointer.TogglePointer (Boolean state) (at Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_BezierPointer.cs:100)
VRTK.VRTK_WorldPointer.EnablePointerBeam (System.Object sender, ControllerInteractionEventArgs e) (at Assets/SteamVR_Unity_Toolkit/Scripts/Abstractions/VRTK_WorldPointer.cs:152)
VRTK.VRTK_ControllerEvents.OnAliasPointerOn (ControllerInteractionEventArgs e) (at Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_ControllerEvents.cs:163)
VRTK.VRTK_ControllerEvents.EmitAlias (ButtonAlias type, Boolean touchDown, Single buttonPressure, System.Boolean& buttonBool) (at Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_ControllerEvents.cs:277)
VRTK.VRTK_ControllerEvents.Update () (at Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_ControllerEvents.cs:395)

**Comment by rocky1138** [comment]
After wrapping an if-block around line 100 as you've suggested, I get a new error:
```
MissingReferenceException: The object of type 'GameObject' has been destroyed but you are still 
trying to access it.
Your script should either check if it is null or you should not destroy the object.
VRTK.VRTK_BezierPointer.ProjectDownBeam () (at Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_BezierPointer.cs:220)
VRTK.VRTK_BezierPointer.Update () (at Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_BezierPointer.cs:55)
```

**Comment by D3m0n92** [comment]
Same error on latest version of VRTK on git, when change scene.

**Comment by bddckr** [comment]
@D3m0n92 https://github.com/thestonefox/VRTK/issues/1145
