### ISSUE TITLE
Pressing System button forcely drops grabbed objects.

### ISSUE THREAD

**Issue by jhorikawa** [thestonefox/SteamVR_Unity_Toolkit#301]
It forcely drops the grabbed objects when pressing system button on the controller even if the object is undroppable. I cannot seem to regrab with the same controller after it's been forcely dropped.

**Comment by thestonefox** [comment]
I think this is because the system button calls the OnDisable script (which is supposed to make you drop things if you disable a script).

I think this will need improving to listen to the system button press and ignore the force drop.

**Comment by thestonefox** [comment]
Fixed with https://github.com/thestonefox/SteamVR_Unity_Toolkit/commit/29a974134ae642e3f1d3b5270ee261c0111bc955

**Comment by LordHorusNL** [comment]
This issue seems to be back for me.

Environment

VRTK github latest release
Unity 5.5.2f1

Steps to reproduce

- Open up 005_Controller_BasicObjectGrabbing.
- Select the green cube and **set Hold button to grab**: False, **Valid drop**: No_Drop.
- Remove VRTK_FixedJointGrabAttach.
- Add VRTK_ChildofControllerGrabAttach and select precision grab.

Expected behavior

The object should keep following the controller even after pressing the system button, no matter if set to kinematic or us gravity.

Current behavior

When us gravity is set the object often fall to the ground, and if kinematic is set i am often unable to swap the object between controllers until i press the system button again!

**Comment by bddckr** [comment]
@LordHorusNL Did you drag and drop the new grab attach script into the field of the InteractableObject?

**Comment by thestonefox** [comment]
@LordHorusNL I cannot recreate the issue following your steps.

Are you forcing the is Kinematic to be false via script? If you do that then you will force the object to drop so that isn't a bug.

I also cannot get the object to drop when updating the allowed grab controller at runtime either.

**Comment by LordHorusNL** [comment]
Ok so i created a new clean project only imported the latest version of steamvr and latest VRTK from github.

Still the same problem, the object falls to the ground after pressing the system button.

005_Controller_BasicObjectGrabbing
Remove fixedjointgrab
add childofcontroller
leave all settings to default.

Still falls

The only thing i did not update was Unity itself, will see if that fixed the issue

**Comment by thestonefox** [comment]
I've also tried in 5.5.2 and I still cannot recreate the issue.

Are you on the latest github master version?

**Comment by LordHorusNL** [comment]
Yes using the latest github master. Reinstalled unity still the same.

I don't need to drop items for the project i'm working on, weapons stay attached to the controllers. So at the moment it's not a big problem for me.

I'll keep an eye on it an see if the issue persists

**Comment by thestonefox** [comment]
maybe see if someone else can recreate the issue. I'm having no issues with it at all.

**Comment by LordHorusNL** [comment]
Ok i did a fresh install off windows, upgraded to windows 10. formatted all my drives. installed only steam and unity/Visual Studio 2015 and vrtk

The object still drops when pressing the system button, also the ignore colliders option seems to not work at all anymore, and i know it did for me a few weeks back when you implemented it.

The object is surpose to keep following your controller after pressing system button right? and not focibly drop.

**Comment by thestonefox** [comment]
@LordHorusNL can you re-write the exact steps you're doing to reproduce this problem.

maybe with a video of showing the steps you're following? Something is amiss as no one else seems to be able to recreate this issue.

**Comment by LordHorusNL** [comment]
OK after a new full windows 7 install, this is what i did.

- Install steam + Steamvr (not beta)
- Download Unity 5.5.2f1
- Install with default options (Unity 5.5.2f1, Documentation, Starndard Assets, Microsoft visual studio tools for unity)
- Startup unity
- Make a fresh project.
- Download the latest version of steamvr of the asset store and close unity.
- Download the latest VRTK of github. master offcourse.
- Place the VRTK folder from VRTK-Master in my test project assets folder.
- Open my project in unity.
- Open 005_Controller_BasicObjectGrabbing
- Select green cube and on the VRTK_Interactable object script uncheck "Hold button to grab"
- Press play

No other steps taken.

And after i grab the cube and press the system button on either controller. drop!

I even tried it without any Firewall/Antivirus software running. stil nothing.

**Comment by thestonefox** [comment]
Try opening the VRTK project directly rather than copying to your project. There may be something in your project causing the issue you're seeing?

**Comment by LordHorusNL** [comment]
Tried that same problem

**Comment by thestonefox** [comment]
Your instructions will cause the cube to drop on system button press.

You haven't selected "Valid Drop = No Drop"

**Comment by LordHorusNL** [comment]
Ahh ok, so the cube will only stay with the controller when No Drop is selected? and i need to code a script to drop the object myself afterwards.

If i set the object to No Drop, it indeed stays with the object, however after a system button press, the object jumps to the original controller used to pick it up.

So if i pick it up with right and swap the object left, and then press system button. the object will jump back to the right hand.

**Comment by thestonefox** [comment]
That sounds like a different issue.

I suggest raising a new issue with steps to reproduce that problem.

Sounds like an issue with not setting the object state when it's grabbed but then disabled due to the system button being pressed.

**Comment by LordHorusNL** [comment]
Ok will do.

So just to be clear, it's currently not possible to create a object that you can pick up and drop again,
that actually sticks with your controller after a system button press?

Only possible when dropping in a "drop zone" am i right?

**Comment by thestonefox** [comment]
You can either force grab again when the game unpauses or you can turn off SteamVR pausing your game when you press the system button.

To do the latter, just add the SteamVR prefab to your scene and untick the pause option.

**Comment by LordHorusNL** [comment]
Ahh i did not know about the pause button!

Thanks you very much, that should fix my issue.
