### ISSUE TITLE
Scene 011 Headset collision fading not working

### ISSUE THREAD

**Issue by kjm16** [thestonefox/SteamVR_Unity_Toolkit#62]
Nothing happens when I put my head through the example walls.
Unity 5.4.0b17

**Comment by thestonefox** [comment]
I think some steam vr stuff has been deprecated in unity 5.4 so they've removed stuff that's breaking certain things. I have another 5.4 issue elsewhere that's probably the same problem as this. If I fix that it may solve this too.

**Comment by kjm16** [comment]
The fading does work on 5.3.4f1. It would be best to get all these issues fixed in 5.4 since that's what everyone will be using next month.

**Comment by thestonefox** [comment]
Yeah as I said there is some deprecated stuff in 5.4 that's breaking things. Once that's resolved it should solve this too.

**Comment by thestonefox** [comment]
Ok so I have 5.4 installed now.

I can see what's happening. Originally the CameraRig prefab was arranged like:

  * [CameraRig]
   * Camera (Head)
     * Camera (eye)
     * Camera (ears)

And the Fade script went on the "Camera (Head)" element.

However, in Unity 5.4 at runtime that CameraRig now changes to look like:

  * [CameraRig]
   * Camera (eye)
     * Camera (ears)
     * [DISABLED] Camera (Head)

Not sure why it now changes the structure of the CameraRig and indeed disables the Camera head.

If you put the Fade script on the "Camera (eye)"  child object then fading works in unity 5.4

**Comment by kjm16** [comment]
Sweet! Just tested it works now! Thanks!

**Comment by EnniArt** [comment]
The scene still doesn't work for me. I even manually put the collision fade script on Camera (eye) and Camera(Head) but nothing seems to work
